### PR TITLE
Use logging framework encoder, remove JCL/SLF4J

### PR DESCRIPTION
**Pull request by wsargent**
This PR changes chronicle logger to leverage the logging framework infrastructure more.  It's large, and I completely understand if it's too big to take.  Still... feedback always welcome.

Major changes:

* Events now take an `entry` of `byte[]` which contains the result of the logging framework's encoder.  This allows the chronicle logger to append to chronicle-queue, while allowing substitutions and input to come from the encoder directly -- i.e. customized structured logging from logback-logstash-encoder.
* Log levels are a reflection of the underlying log framework level, and are represented as an `int32`.  Different logging frameworks have different log levels or even custom levels, and the `ChronicleLoggingLevel` is removed.
* LogReader moved to the core, as it has to be able to decompress bytes, centralized the chronicat and chronitail logic and added a StdOutProcessor.
* There's an optional entry "type" which can represent entries with a content type, like HTTP headers -- for example, JSON can be represented as "application/json" or even higher level "application/ld+json".  Right now it assumes text/plain and returns a `String` but can return other objects.  The standard charset is UTF-8 if not applied.
* Also an optional entry "encoding" which is like HTTP content encoding, which can indicate when compression has been applied to bytes.  Only zstandard compression (not garbage free, but the API looks promising) is in there right now.

Things removed:

* The JCL and SLF4J implementation are removed, as they don't have an underlying representation and the chronicle wire object representation is buggy ("throwable"/"args" can throw exceptions from chronicat, and the representation is not stable between jdk 8/11 -- also "primitive: void" errors of some kind?)  There's always the option of adding a "chronicle-wire encoder" which writes the bytes of an entry as "message"/"throwable"/"args" as before.

### CODE REVIEW

**Comment by dpisklov** [comment]
@wsargent hello, that was a huge piece of work - any particular reason you decided to close the PR?

**Comment by wsargent** [comment]
@dpisklov after 22 days and 108 classes I figured it was a bit of a ridiculous PR...

**Comment by dpisklov** [comment]
@wsargent yes it would be hard to review but probably well worth it... In what state the code was? I can merge it into a branch.

**Comment by wsargent** [comment]
Working and passing tests at least.  I'll bring up the branch again so you can review it

**Pull request closed without merging**
